### ISSUE TITLE
Page elements get selected by double click on background

### ISSUE THREAD

**Issue by skurzhanskyi** [sergei-zelinsky/sergei-zelinsky.github.io#1]
Example:

![image](https://user-images.githubusercontent.com/17638837/35906557-a39a543e-0bf3-11e8-8a78-7218e7019d8c.png)

**Comment by skurzhanskyi** [comment]
It's very difficult to reproduce, so I'll make a video later.

**Comment by sergei-zelinsky** [comment]
Fixed in https://github.com/sergei-zelinsky/sergei-zelinsky.github.io/commit/145e3121b4136a2d4a63866a72d5fd312ae88515.

Thanks!
@skurzhanskyi
